# LinearRegression { #savvi.linear_regression.LinearRegression }

```python
linear_regression.LinearRegression(self, alpha, p, phi=1)
```

Treatment effect tests from @lindon2024anytimevalidlinearmodelsregression.

Coefficients are calculated using the Recursive Least Squares algorithm.

See [example](../examples/linear_regression.qmd).

## Attributes {.doc-section .doc-section-attributes}

| Name       | Type       | Description                                 |
|------------|------------|---------------------------------------------|
| beta       | np.ndarray | Estimate of regression coefficients.        |
| covariance | np.ndarray | Estimate of covariance matrix.              |
| yty        | float      | Sum of squared response values.             |
| Xty        | np.ndarray | Sum of products of covariates and response. |

## Methods

| Name | Description |
| --- | --- |
| [calculate_conf_int](#savvi.linear_regression.LinearRegression.calculate_conf_int) | Calculate confidence intervals for the coefficients. |
| [calculate_p_value](#savvi.linear_regression.LinearRegression.calculate_p_value) | Calculate p-values for the coefficients. |
| [nu](#savvi.linear_regression.LinearRegression.nu) | Degrees of freedom. |
| [predict](#savvi.linear_regression.LinearRegression.predict) | Predict values for given covariates. |
| [sigma](#savvi.linear_regression.LinearRegression.sigma) | Estimate the standard deviation of the error term. |
| [sse](#savvi.linear_regression.LinearRegression.sse) | Compute the Sum of Squared Errors (SSE). |
| [standard_errors](#savvi.linear_regression.LinearRegression.standard_errors) | Estimate the standard errors of the coefficients. |
| [t_stats](#savvi.linear_regression.LinearRegression.t_stats) | Calculate the t statistics of the coefficients. |
| [update](#savvi.linear_regression.LinearRegression.update) | Update the model with new data. |
| [z2](#savvi.linear_regression.LinearRegression.z2) | Calculate the squared z-scores. |

### calculate_conf_int { #savvi.linear_regression.LinearRegression.calculate_conf_int }

```python
linear_regression.LinearRegression.calculate_conf_int()
```

Calculate confidence intervals for the coefficients.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description                                |
|--------|------------|--------------------------------------------|
|        | np.ndarray | Confidence intervals for the coefficients. |

### calculate_p_value { #savvi.linear_regression.LinearRegression.calculate_p_value }

```python
linear_regression.LinearRegression.calculate_p_value()
```

Calculate p-values for the coefficients.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description                    |
|--------|------------|--------------------------------|
|        | np.ndarray | P-values for the coefficients. |

### nu { #savvi.linear_regression.LinearRegression.nu }

```python
linear_regression.LinearRegression.nu()
```

Degrees of freedom.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description         |
|--------|--------|---------------------|
|        | int    | Degrees of freedom. |

### predict { #savvi.linear_regression.LinearRegression.predict }

```python
linear_regression.LinearRegression.predict(X)
```

Predict values for given covariates.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type       | Description           | Default    |
|--------|------------|-----------------------|------------|
| X      | np.ndarray | Matrix of covariates. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description       |
|--------|------------|-------------------|
|        | np.ndarray | Predicted values. |

### sigma { #savvi.linear_regression.LinearRegression.sigma }

```python
linear_regression.LinearRegression.sigma()
```

Estimate the standard deviation of the error term.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                           |
|--------|--------|-------------------------------------------------------|
|        | float  | Estimate of the standard deviation of the error term. |

### sse { #savvi.linear_regression.LinearRegression.sse }

```python
linear_regression.LinearRegression.sse()
```

Compute the Sum of Squared Errors (SSE).

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description   |
|--------|--------|---------------|
|        | float  | SSE value.    |

### standard_errors { #savvi.linear_regression.LinearRegression.standard_errors }

```python
linear_regression.LinearRegression.standard_errors()
```

Estimate the standard errors of the coefficients.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description                                          |
|--------|------------|------------------------------------------------------|
|        | np.ndarray | Estimate of the standard errors of the coefficients. |

### t_stats { #savvi.linear_regression.LinearRegression.t_stats }

```python
linear_regression.LinearRegression.t_stats()
```

Calculate the t statistics of the coefficients.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description                       |
|--------|------------|-----------------------------------|
|        | np.ndarray | T statistics of the coefficients. |

### update { #savvi.linear_regression.LinearRegression.update }

```python
linear_regression.LinearRegression.update(xy)
```

Update the model with new data.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type                       | Description                             | Default    |
|--------|----------------------------|-----------------------------------------|------------|
| xy     | Tuple\[np.ndarray, float\] | Tuple of response and covariate values. | _required_ |

### z2 { #savvi.linear_regression.LinearRegression.z2 }

```python
linear_regression.LinearRegression.z2()
```

Calculate the squared z-scores.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type       | Description       |
|--------|------------|-------------------|
|        | np.ndarray | Squared z-scores. |